Feature/prgs feedback april 29
Ucommercenet/Ucommerce.Sitefinity.UI pull request #33
Opened 2020-05-18 04:35 UTC by timgaunt

2020-05-20 10:40 UTC, GeorgeAlexandruD requested changes

2020-05-20 10:40 UTC, GeorgeAlexandruD commented on Ucommerce.Sitefinity.UI/Mvc/Model/CartModel.cs
> +                    ProductName = product.DisplayName(),
I can see it has changed to use the product display name, but after a search of the code, there are two places where orderLine.ProductName is still being used.

ConfirmationEmailModel Line:68
BasketController Line:149

Is this intended? Why is it changed in only some places but not in others?

Also, looked through the code, in AddToBasket Pipeline, the display name is set on the order. So this seems unnecessary.

2020-05-20 10:40 UTC, GeorgeAlexandruD commented on Ucommerce.Sitefinity.UI/Mvc/Model/MiniBasketModel.cs
> +        private string GettPageAbsoluteUrl(Guid pageId)
GetPageAbsoluteURL

2020-05-20 10:40 UTC, GeorgeAlexandruD commented on Ucommerce.Sitefinity.UI/assets/src/js/widgets/review-list.js
> +                        this.hasValue(response.data.Data) &&
I can see there is a group of nested data.

Where does it come from and is it possible to flatten it or remodel it for more clarity?

2020-05-20 10:40 UTC, GeorgeAlexandruD commented on Quantum/Mvc/Views/Address/Index.cshtml.orig
> +<<<<<<< HEAD
It seems it is not merged or the file is committed by mistake.

2020-05-20 10:40 UTC, GeorgeAlexandruD commented on Ucommerce.Sitefinity.UI/assets/src/js/widgets/products.js
> +    if (scriptElement) {variants
Dangling "variants" word

2020-05-20 10:40 UTC, GeorgeAlexandruD commented on Ucommerce.Sitefinity.UI/Mvc/Model/CartModel.cs
> +                voucherPropValue = string.Join(",", discountCodesList);
Not sure if there is a correlation between joining campaign item names of discounts and setting them as property values.

2020-05-21 19:42 UTC, timgaunt commented on Quantum/Mvc/Views/Address/Index.cshtml.orig
> +<<<<<<< HEAD
I'd imagine so, orig files are usually excluded. I've deleted it and added an ignore

2020-05-21 19:46 UTC, timgaunt commented on Ucommerce.Sitefinity.UI/Mvc/Model/CartModel.cs
> +                    ProductName = product.DisplayName(),
Agreed this isn't needed. It's sometimes done when the cart item has been around for a long time and the admins change names etc but I can't imagine that's the case here. I guess the only other reason was that the product has been retrieved above so it was available. I've removed it anyway and changed to `orderLine.ProductName`

2020-05-21 20:46 UTC, timgaunt commented on Ucommerce.Sitefinity.UI/Mvc/Model/CartModel.cs
> +                voucherPropValue = string.Join(",", discountCodesList);
Agreed, that should be done in the `RemoveDiscount` logic but I think we'll want to review this block as there's also a block above which I think could be removed:

```
var prop = basket.OrderProperties.FirstOrDefault(v => v.Key == "voucherCodes");
if (prop != null)
{
	prop.Value = prop.Value.Replace(item + ",", string.Empty);
	prop.Save();
}
```

Marking this as closed as I think we'll overhaul aspects of this seperately

2020-05-21 20:55 UTC, timgaunt commented on Ucommerce.Sitefinity.UI/assets/src/js/widgets/review-list.js
> +                        this.hasValue(response.data.Data) &&
`response.data` is the standard JavaScript response.

`response.data.Data` is just a bad name I think, it comes from here: https://github.com/Ucommercenet/Ucommerce.Sitefinity.UI/blob/3aa4b817a5aa8476d59c64c0335feb74f3df59a1/Ucommerce.Sitefinity.UI/Api/Model/OperationStatusDTO.cs#L20 and is used elsewhere in the project so I would suggest leaving that for the time being.

`response.data.Data.data` - this comes from here: https://github.com/Ucommercenet/Ucommerce.Sitefinity.UI/blob/aec6acb797a07fc329c1a35b658b75caba4f9da9/Ucommerce.Sitefinity.UI/Mvc/Controllers/ProductReviewsController.cs#L52 and can be changed without a concern (done)

`response.data.Data.data.Reviews` - comes from the ViewModel as it's just assigning the entire view model. I can't see `Ip` being used so I've just assigned the data to the response. It's still not ideal but at lease it's now `response.data.Data.Reviews`

2020-05-22 07:56 UTC, GeorgeAlexandruD approved these changes

2020-05-22 07:56 UTC, merged